# Generated by Django 3.2.5 on 2021-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_boardtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='boardtype',
            new_name='boardtypes',
        ),
    ]
