# Generated by Django 3.2.5 on 2021-07-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_boardtype_board_boardtypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='boardtypes',
            new_name='boardtype',
        ),
    ]
